version: '3'
services:
  streamlit:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    build:
      context: .
      dockerfile: psql.dockerfile
      
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
