version: '3'
networks: 
    dsa4213_ppt_gen:
services:
  streamlit:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    build:
      context: .
      dockerfile: psql.dockerfile
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    env_file:
      - .env
    environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d

      # - postgres-data:/var/lib/postgresql/data
    networks:
      - dsa4213_ppt_gen


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on: 
      - postgres
    networks:

      - dsa4213_ppt_gen

# volumes:
#   postgres-data:

