version: '3'
services:
  streamlit:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: psql.dockerfile
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
